In [1]:
import pandas as pd

df = pd.read_csv('submission.csv')
df

ID  0  1  2  3  4  5  6  7  8  ...  19866  19867  19868  19869  19870  \
0   0  0  0  0  1  1  1  2  2  2  ...   2459   2461   2462   2462   2462   
1   1  0  0  0  1  1  1  2  2  2  ...     -1     -1     -1     -1     -1   
2   2  0  0  0  1  1  1  2  2  2  ...     -1     -1     -1     -1     -1   
3   3  0  0  0  1  1  1  2  2  2  ...     -1     -1     -1     -1     -1   
4   4  0  0  0  1  1  1  2  2  2  ...     -1     -1     -1     -1     -1   
5   5  0  0  1  1  1  2  2  2  2  ...     -1     -1     -1     -1     -1   

   19871  19872  19873  19874  19875  
0   2462   2465   2469   2471   2483  
1     -1     -1     -1     -1     -1  
2     -1     -1     -1     -1     -1  
3     -1     -1     -1     -1     -1  
4     -1     -1     -1     -1     -1  
5     -1     -1     -1     -1     -1  

[6 rows x 19877 columns]

In [2]:
from baseline import inference_wrapper
import torch
import torch_geometric.utils as pyg_utils

aug_data = torch.load("data\data_augmented.pt")
result = inference_wrapper(aug_data, "model.pt")
print(result)

{'train_acc': tensor(0.9857), 'val_acc': tensor(0.8000)}


In [11]:
import pickle
import os
import torch

def update_edge(data, adj_matrix):
    if not isinstance(adj_matrix, torch.Tensor):
        adj_matrix = torch.from_numpy(adj_matrix).to_sparse()
    edge_idx_update = adj_matrix.coalesce().indices()
    print(edge_idx_update)
    data.edge_index = edge_idx_update
    return data

raw_data = torch.load("data\data.pt")
graph_files = os.listdir("graphs")
for file in graph_files:
    with open(os.path.join("graphs", file), "rb") as f:
        adj = pickle.load(f)
    data = update_edge(raw_data, adj)
    result = inference_wrapper(data, "model.pt")
    print(result)

tensor([[   0,    0,    0,  ..., 2484, 2484, 2484],
        [   0,  575, 1722,  ..., 1353, 2483, 2484]])
{'train_acc': tensor(0.9857), 'val_acc': tensor(0.7920)}
tensor([[   0,    0,    0,  ..., 2484, 2484, 2484],
        [   1,    2,    3,  ..., 2481, 2482, 2483]])
{'train_acc': tensor(0.1429), 'val_acc': tensor(0.2780)}
tensor([[   0,    0,    0,  ..., 2484, 2484, 2484],
        [   1,    2,    3,  ..., 2481, 2482, 2483]])
{'train_acc': tensor(0.1429), 'val_acc': tensor(0.2780)}
tensor([[   0,    0,    0,  ..., 2484, 2484, 2484],
        [   1,    2,    3,  ..., 2481, 2482, 2483]])
{'train_acc': tensor(0.1429), 'val_acc': tensor(0.2780)}
tensor([[   0,    0,    0,  ..., 2484, 2484, 2484],
        [   1,    2,    3,  ..., 2481, 2482, 2483]])
{'train_acc': tensor(0.1429), 'val_acc': tensor(0.2780)}
tensor([[   0,    0,    0,  ..., 2484, 2484, 2484],
        [   1,    2,    3,  ..., 2481, 2482, 2483]])
{'train_acc': tensor(0.1429), 'val_acc': tensor(0.2780)}
tensor([[   0,    0,    0,  